FROM debian:jessie

RUN dpkg-divert --local --rename --add /sbin/initctl && ln -sf /bin/true /sbin/initctl

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends wget \
    && echo "deb http://packages.dotdeb.org jessie all" > /etc/apt/sources.list.d/dotdeb.list \
    && echo "deb-src http://packages.dotdeb.org jessie all" >> /etc/apt/sources.list.d/dotdeb.list \
    && wget -O - http://www.dotdeb.org/dotdeb.gpg | apt-key add - \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        php7.0-zip php7.0-xsl php7.0-xmlrpc php7.0-xml php7.0-tidy php7.0-soap \
        php7.0-redis php7.0-recode php7.0-readline php7.0-pspell php7.0-opcache \
        php7.0-mysql php7.0-msgpack php7.0-memcached php7.0-mcrypt php7.0-mbstring \
        php7.0-json php7.0-intl php7.0-imagick php7.0-geoip php7.0-gd php7.0-fpm \
        php7.0-curl php7.0-cli php7.0-cgi php7.0-bz2 php7.0-bcmath php7.0 \
        nginx supervisor curl \
    && curl --insecure -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/bin/composer \
    && rm -r /var/lib/apt/lists/*

COPY ./containers/config-files/php.cli.ini /etc/php/7.0/cli/php.ini
COPY ./containers/config-files/php.fpm.ini /etc/php/7.0/fpm/php.ini

COPY ./containers/config-files/nginx.conf /etc/nginx/nginx.conf
COPY ./containers/config-files/default.conf /etc/nginx/sites-enabled/default

COPY ./containers/config-files/www.conf /etc/php/7.0/fpm/pool.d/www.conf

COPY ./containers/config-files/supervisor.nginx.conf /etc/supervisor/conf.d/nginx.conf
COPY ./containers/config-files/supervisor.core.conf /etc/supervisor/conf.d/core.conf
COPY ./containers/config-files/supervisor.php-fpm.conf /etc/supervisor/conf.d/php-fpm.conf


COPY . /app/
RUN chown www-data:www-data -R /app/

EXPOSE 80 443

CMD ["/usr/bin/supervisord", "-n"]